# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def shared_pods
    # Pods for Companies
    # Debugging
    pod 'SwiftLint'
end

target 'CompaniesTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'Companies' do
    # Shared pods
    shared_pods
end

target 'CompaniesUITests' do
    inherit! :search_paths
    # Pods for testing
end


